### ISSUE TITLE
Examples for typescript with angular

### ISSUE THREAD

**Issue by IJustDev** [RonenNess/RPGUI#12]
I don't know if my problem is my fault. I'm currently trying to implement RPGUI in angular. CSS works, but I can't use the js part in typescript.
Regardless of whether it's my fault or not could anyone please provide a typescript/angular example ?

**Comment by Dicktare** [comment]
> I don't know if my problem is my fault. I'm currently trying to implement RPGUI in angular. CSS works, but I can't use the js part in typescript.
> Regardless of whether it's my fault or not could anyone please provide a typescript/angular example ?

Hi,
This might be late, but a quick fix is to add the css to angular.json in the style section

"
-----------
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css",
              "dist/rpgui.css"
            ],
            "scripts": []
---------------------------
"

**Comment by IJustDev** [comment]
Thank you very much. It's never to late. Somebody will may need this.

Should we add a section for angular users to the README?

**Comment by IJustDev** [comment]
See following pull request: #13

**Comment by IJustDev** [comment]
#13 was merged. Issue fixed!
