### ISSUE TITLE
SASS for CSS ?

### ISSUE THREAD

**Issue by titoasty** [RonenNess/RPGUI#4]
Why not using SASS to write CSS ?
It would be easier to maintain, especially for prefixes AND you could put variables for ui configuration (like font family, font size, some custom colors...)

**Comment by titoasty** [comment]
after playing with the code, you should definitely use gulp to automatize build system (and definitely sass for css)

**Comment by RonenNess** [comment]
Merged your poll request that included scss and gulp.
Thanks!
