### ISSUE TITLE
rpgui.js Script Printing Select Dropdown Menu Twice

### ISSUE THREAD

**Issue by green6060** [RonenNess/RPGUI#9]
I haven't quite figured out why yet, but for some reason the rpgui.js is printing any box with a SELECT tag twice. I'll upload a picture. It might have to do with the fact that I'm trying to build my web app using ruby on rails (I built the page prior to incorporating it into a Ruby on Rails app,  and it was working fine up until the incorporation.) 
![double_printing_error](https://user-images.githubusercontent.com/31931839/44938012-8facae80-ad39-11e8-80f2-a5533234e545.PNG)
![double_printing_error_code](https://user-images.githubusercontent.com/31931839/44938013-8facae80-ad39-11e8-8ccd-1ea46986d32d.PNG)

**Comment by RonenNess** [comment]
Which browser? Does it also happen here: http://ronenness.github.io/RPGUI/#drop-and-list?

Thanks,

**Comment by fabge** [comment]
Hello @RonenNess,
I am experiencing the same issue when using Django.
I cannot really figure out why.

When using the dynamic element creation, the dropdown is created four times, not only twice..
```html
// will create a dropdown RPGUI element from a <select> tag with id some_id
var select = document.getElementById("some_id");
RPGUI.create(select, "dropdown");
```

<img width="907" alt="image" src="https://user-images.githubusercontent.com/21140791/150874575-5b47c871-339d-4f45-a72d-90d78a9bc255.png">

**Comment by fabge** [comment]
I actually do experience the exact same issue when using the Django Framework...
